name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install -y libsqlite3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
    - name: Clippy
      run: cargo clippy
    - name: Coverage
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
