name: macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install sqlite3
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Build
      run: PATH=$PATH:$HOME/.cargo/bin cargo build --verbose
    - name: Run tests
      run: PATH=$PATH:$HOME/.cargo/bin cargo test --verbose -- --test-threads=1
